# Generated by Django 3.2 on 2022-08-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='title',
            field=models.CharField(max_length=50, verbose_name='post'),
        ),
    ]
