# Generated by Django 3.2 on 2022-07-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created', 'name_en'], 'verbose_name': '상품', 'verbose_name_plural': '상품'},
        ),
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=120, verbose_name='영어이름'),
        ),
    ]
