# Generated by Django 3.2 on 2022-08-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220728_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='product/%Y/%m/%d'),
        ),
    ]
